Use a bit operator for bit masking.
In YEBinary::type ()
[   57s] YExpression.cc:1454:26: error: enum constant in boolean context [-Werror=int-in-bool-context]
[   57s]      if (m_decl->flags && DECL_FLEX)
[   57s]                           ^~~~~~~~~

Fortunately, this bug never triggered, because all existing YEBinary
instances either had no m_decl->flags, or they were exactly equal to
DECL_FLEX (for list<T> + list<T>, and for list<T> + T).