clang: Added a missing include.
[  114s] In file included from Y2CCDummyAgent.cc:8:
[  114s] ../../libscr/src/include/scr/Y2AgentComponent.h:129:53: error: calling 'asPath' with incomplete return type 'YCPPath'
[  114s]             return getSCRAgent ()-> Read (args->value (0)->asPath (), args->size() > 1 ? args->value (1) : YCPNull ()) ;
[  114s]                                           ~~~~~~~~~~~~~~~~~^~~~~~~~~
[  114s] ../../libycp/src/include/ycp/YCPValue.h:206:13: note: 'asPath' declared here
[  114s]     YCPPath asPath() const;
[  114s]             ^
[  114s] ../../libycp/src/include/ycp/YCPElement.h:51:7: note: forward declaration of 'YCPPath'
[  114s] class YCPPath;
[  114s]       ^